<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Http\RequestHandlers\TomSelectPlace;

/**
 * @var Tree                $tree
 * @var \Illuminate\Support\Collection<\Fisharebest\Webtrees\Place>   $top_places
 */

?>

<!--  MAPPER_FILT_TOP_PLACES -->
<div class="row">
    <label class="col-sm-3 col-form-label" for="mapper_filt_top_places">
        <?= I18N::translate('Parent places') ?>
    </label>
    <div class="col-sm-9">
        <select
            autocomplete="off"
            class="form-select tom-select"
            id="mapper_filt_top_places"
            name="mapper_filt_top_places[]"
            multiple="multiple"
            data-url="<?= e(route(TomSelectPlace::class, ['tree' => $tree->name(), 'at' => ''])) ?>"
        >
        <?php foreach ($top_places as $top_place) : ?>
            <option value="<?= $top_place->id() ?>" selected>
                <?= view('selects/place', ['place' => $top_place]) ?>
            </option>
        <?php endforeach; ?>
        </select>
        <p class="form-text">
            <?= I18N::translate('Filter on places belonging to those parent places.') ?>
        </p>
    </div>
</div>

<?php View::push('javascript') ?>
<script>

webtrees.initializeTomSelect(document.getElementById('mapper_filt_top_places'));

</script>
<?php View::endpush() ?>