<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Http\RequestHandlers\Select2Place;

/**
 * @var Tree                $tree
 * @var Collection<Place>   $top_places
 */

?>

<!--  MAPPER_FILT_TOP_PLACES -->
<div class="row">
    <label class="col-sm-3 col-form-label" for="mapper_filt_top_places">
        <?= I18N::translate('Parent places') ?>
    </label>
    <div class="col-sm-9">
        <select
            class="form-select select2"
            id="mapper_filt_top_places"
            name="mapper_filt_top_places[]"
            multiple="multiple"
            data-ajax--delay="<?= e(Select2Place::AJAX_DELAY) ?>"
            data-minimum-input-length="<?= e(Select2Place::MINIMUM_INPUT_LENGTH) ?>"
            data-ajax--type="POST"
            data-ajax--url="<?= e(route(Select2Place::class, ['tree' => $tree->name()])) ?>"
            data-allow-clear="true"
            data-placeholder=""
        >
        <?php foreach ($top_places as $top_place) : ?>
            <option value="<?= e($top_place->id()) ?>" selected>
                <?= view('selects/place', ['place' => $top_place]) ?>
            </option>
        <?php endforeach; ?>
        </select>
        <p class="form-text">
            <?= I18N::translate('Filter on places belonging to those parent places.') ?>
        </p>
    </div>
</div>

<?php View::push('javascript') ?>
<script>

$('#mapper_filt_top_places').select2();

</script>
<?php View::endpush() ?>