<?php

use Fisharebest\Webtrees\Html;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use MyArtJaub\Webtrees\Module\Certificates\Http\RequestHandlers\AutoCompleteFile;

/**
 * @var string      $module_name
 * @var Tree        $tree
 * @var string      $id
 * @var string      $name
 * @var string[][]  $cities
 * @var string      $value
 * @var string      $value_city
 * @var string      $value_file
 * @var string      $js_script_url
 */

$attributes_hidden = [
    'id'                      => $id,
    'name'                    => $name,
    'value'                   => $value,
    'type'                    => 'hidden',
];

$attributes_cert_file = [
    'autocomplete'                  =>  'off',
    'class'                         =>  'form-control',
    'id'                            =>  $id . '-file',
    'name'                          =>  'edit-_ACT-file',
    'value'                         =>  $value_file,
    'type'                          =>  'text',
    'data-autocomplete-certif-url'  =>  route(AutoCompleteFile::class, ['tree'  => $tree->name()]),
];

?>

<?= view($module_name . '::components/select-city', ['cities' => $cities, 'id' => $id . '-city', 'name' => 'edit-_ACT-city', 'selected_city' => $value_city]) ?>

<input <?= Html::attributes($attributes_cert_file) ?>>
<input <?= Html::attributes($attributes_hidden) ?>>

<?php View::pushunique('javascript') ?>

<script src="<?= e($js_script_url) ?>"></script>

<?php View::endpushunique() ?>

<?php View::push('javascript') ?>

<script>

$(document.getElementById('<?= $id ?>-city')).change(function(){
    $(document.getElementById('<?= $id ?>-file')).val('').trigger('change');
});

$(document.getElementById('<?= $id ?>-file')).change(function(){
    if(this.value.length > 0){
        $(document.getElementById('<?= $id ?>')).val($(document.getElementById('<?= $id ?>-city')).find(':selected').text() + '/' + this.value);
    }
    else{
        $(document.getElementById('<?= $id ?>')).val('');
    }
});

</script>

<?php View::endpush() ?>
