<?php

use Fisharebest\Webtrees\View;

/**
 * @var string[][]  $cities
 * @var string      $selected_city
 * @var string|null $class
 * @var string|null $id
 * @var string      $name
 * @var bool|null   $disabled
 * @var bool|null   $required
 */

?>

<div class="maj-certificate-tom-select">
    <select
        autocomplete="off"
        class="form-select tom-select maj-tom-select <?= $class ?? '' ?>"
        required="required"
        id="<?= e($id ?? $name) ?>"
        name="<?= e($name) ?>"
        <?= ($disabled ?? false) ? 'disabled' : '' ?>
        <?= ($required ?? false) ? 'required' : '' ?>
    >
        <?php foreach ($cities as $city) :  ?>
        <option value="<?= $city[0] ?>" <?= $selected_city === $city[1] ? 'selected' : '' ?>><?= $city[1] ?></option>
        <?php endforeach; ?>
    </select>
</div>
