<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use MyArtJaub\Webtrees\Module\GeoDispersion\Http\RequestHandlers\GeoAnalysisViewTabs;
use MyArtJaub\Webtrees\Module\GeoDispersion\Views\GeoAnalysisView;

/**
*  @var string          $module_name
 * @var string          $title
 * @var Tree            $tree
 * @var GeoAnalysisView $view
 */
?>

<h2 class="wt-page-title mx-auto"><?= e($title) ?></h2>

<div class="wt-page-content wt-page-content-maj-geodisp-geoanalysisview">
<?php if ($view === null) : ?>
    <?= view($module_name . '::errors/no-geoanalysisview') ?>
<?php else : ?>
    <h3 class="text-center my-4"><?= $view->description() ?></h3>

    <div id="maj-geoanalysisview-tabs" class="maj-content-tabs maj-geodisp-tabs-geoanalysisview">
        <ul class="nav nav-tabs flex-wrap" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" data-bs-toggle="tab" role="tab" href="#maj-geodisp-geoanalysisview-global">
                    <?= I18N::translate('Global data'); ?>
                </a>
            </li>
            
            <li class="nav-item" role="presentation">
                <a class="nav-link" data-bs-toggle="tab" role="tab" href="#maj-geodisp-geoanalysisview-detailed">
                    <?= I18N::translate('Detailed data'); ?>
                </a>
            </li>
        </ul>
        
        <div class="tab-content">
            <div class="tab-pane fade show active" role="tabpanel" id="maj-geodisp-geoanalysisview-global">
                <div class="wt-ajax-load maj-loading-inprocess w-100 mx-auto"></div>
                <div class="maj-loading-complete d-none"></div>
                <div class="maj-loading-error d-none text-center"><?= I18N::translate('An error occurred while retrieving data.') ?></div>
            </div>
            
            <div class="tab-pane fade" role="tabpanel" id="maj-geodisp-geoanalysisview-detailed">
                <div class="wt-ajax-load maj-loading-inprocess w-100 mx-auto"></div>
                <div class="maj-loading-complete d-none"></div>
                <div class="maj-loading-error d-none text-center"><?= I18N::translate('An error occurred while retrieving data.') ?>
            </div>
        </div>
    </div>
    
    <?php View::push('javascript') ?>
    <script>
    
        $.when($.getJSON('<?= e(route(GeoAnalysisViewTabs::class, ['tree' => $tree->name(), 'view_id' => $view->id() ])) ?>'), $.ready)
        .done(function(data, unused) {
            $('#maj-geodisp-geoanalysisview-global').html(data[0].global);
            $('#maj-geodisp-geoanalysisview-detailed').html(data[0].detailed);
            
            $('#maj-geoanalysisview-tabs .maj-loading-complete').removeClass('d-none');
        }).fail(function() {
            $('#maj-geoanalysisview-tabs .maj-loading-error').removeClass('d-none');
        }).always(function() {
            $('#maj-geoanalysisview-tabs .maj-loading-inprocess').addClass('d-none');
        });
    
    </script>
    <?php View::endpush() ?>
    
<?php endif; ?>
</div>
