language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

## Non-sudo environments are faster
sudo: false

## Cache composer and vendor libraries
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - travis_retry composer config github-oauth.github.com "${GITHUB_OAUTH_TOKEN}"

# Coverage testing is slow, so only do it once.
script:
  - if [ $TRAVIS_PHP_VERSION  = 7.4 ]; then vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover tests/clover.xml; fi
  - if [ $TRAVIS_PHP_VERSION != 7.4 ]; then vendor/bin/phpunit -c phpunit.xml.dist; fi

after_script:
  - if [ $TRAVIS_PHP_VERSION = 7.4 ]; then travis_retry php vendor/bin/php-coveralls -v; fi
