language: php

sudo: false

matrix:
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer config github-oauth.github.com "${GITHUB_OAUTH_TOKEN}"
  - travis_retry composer update

script:
  - vendor/bin/phpunit
