<?php

use Fisharebest\Webtrees\I18N;

/**
 * @var bool    $yes
 * @var string  $text_yes
 * @var string  $text_no
 */
?>

<?php if($yes) : ?>
    <i class="fa fa-check"></i><span class="sr-only"><?= isset($text_yes) ? e($text_yes) : e(I18N::translate('Yes')) ?></span>
<?php else : ?>
    <i class="fa fa-times"></i><span class="sr-only"><?= isset($text_no) ? e($text_no) : e(I18N::translate('No')) ?></span>
<?php endif ?>