<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ModulesAllPage;
use Fisharebest\Webtrees\Module\ModuleInterface;

/**
 * @var ModuleInterface $module
 * @var string          $title
 */
?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ModulesAllPage::class) => I18N::translate('Modules'), $title]]) ?>

<h1><?= $title ?></h1>

<form method="post" class="form-horizontal">
    <?= csrf_field() ?>

    <h3><?= I18N::translate('Titles') ?></h3>

    <!--  MAJ_TITLE_PREFIX -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="MAJ_TITLE_PREFIX">
            <?= I18N::translate('Title prefixes') ?>
        </label>
        <div class="col-sm-9">
            <input
                class="form-control"
                dir="auto"
                id="MAJ_TITLE_PREFIX"
                maxlength="255"
                name="MAJ_TITLE_PREFIX"
                type="text"
                placeholder="de |d'|du |of |von |vom |am |zur |van |del |della |t'|da |ten |ter |das |dos |af "
                value="<?= e($module->getPreference('MAJ_TITLE_PREFIX')) ?>"
            >
            <p class="small text-muted">
                <?= I18N::translate('Set possible aristocratic particles to separate titles from the land they refer to (e.g. Earl <strong>of</strong> Essex). Variants must be separated by the character |.') ?>
                <?= I18N::translate('An example for this setting is : <strong>de |d\'|du |of |von |vom |am |zur |van |del |della |t\'|da |ten |ter |das |dos |af </strong> (covering some of French, English, German, Dutch, Italian, Spanish, Portuguese, Swedish common particles).') ?>
            </p>
        </div>
    </div>
    
    <h3><?= I18N::translate('Privacy') ?></h3>
    
    <!-- MAJ_DISPLAY_CNIL -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= I18N::translate('Display French <em>CNIL</em> disclaimer') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'MAJ_DISPLAY_CNIL', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $module->getPreference('MAJ_DISPLAY_CNIL')]) ?>
                <p class="small text-muted">
                    <?= I18N::translate('Enable this option to display an information disclaimer required by the French <em>CNIL</em> for detaining personal information on users.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!--  MAJ_CNIL_REFERENCE -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="MAJ_CNIL_REFERENCE">
            <?= I18N::translate('<em>CNIL</em> reference') ?>
        </label>
        <div class="col-sm-9">
            <input
                class="form-control"
                dir="auto"
                id="MAJ_CNIL_REFERENCE"
                maxlength="255"
                name="MAJ_CNIL_REFERENCE"
                type="text"
                value="<?= e($module->getPreference('MAJ_CNIL_REFERENCE')) ?>"
            >
            <p class="small text-muted">
                <?= I18N::translate('If the website has been notified to the French <em>CNIL</em>, an authorisation number may have been delivered. Providing this reference will display a message on the privacy policy page.') ?>
            </p>
        </div>
    </div>
    
    <div class="row form-group">
        <div class="offset-sm-3 col-sm-9">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
        </div>
    </div>
    
</form>