<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ModulesAllPage;

/**
 * @var string  $title
 * @var string  $trigger_token
 * @var string  $trigger_route
 * @var string  $tasks_data_route
 * @var string  $new_token_route
 * @var string  $js_script_url
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ModulesAllPage::class) => I18N::translate('Modules'), $title]]) ?>

<h1><?= $title ?></h1>

<p><?= I18N::translate('The administration tasks are meant to be run at a regular interval - or as regularly as possible.'); ?></p>
<p>
    <?= I18N::translate('It is sometimes necessary to force the execution of a task.'); ?><br />
    <?= I18N::translate('In order to do so, use the following URL, with the optional parameter <em>%s</em> if you only want to force the execution of one task: ', I18N::translate('task_name')); ?>
</p>
<p>
    <code><?= str_replace(['__TASKNAME__', '__TOKEN__'], ['[' . I18N::translate('task_name') . ']', '<span id="token_url">' . $trigger_token . '</span>'], $trigger_route) ?></code>
</p>
<p>
    <button id="force-token-generate" class="btn btn-primary" onClick="generate_force_token();">
        <div><?= I18N::translate('Regenerate token'); ?></div>
        <i class="fas fa-spinner fa-pulse fa-fw d-none"></i>
    </button>
</p>

<table class="table table-sm table-bordered table-maj-admintasks-list"
    <?= view('lists/datatables-attributes') ?>
>
    <thead>
        <tr>
            <th data-sortable="false" data-searchable="false"><?= I18N::translate('Edit') ?></th>
            <th data-searchable="false"><?= I18N::translate('Enabled') ?></th>
            <th><?= I18N::translate('Task name') ?></th>
            <th data-searchable="false"><?= I18N::translate('Last success') ?></th>
            <th data-searchable="false"><?= I18N::translate('Last result') ?></th>
            <th data-sortable="false" data-searchable="false"><?= I18N::translate('Frequency') ?></th>
            <th data-sortable="false" data-searchable="false"><?= I18N::translate('Remaining occurrences') ?></th>
            <th data-sortable="false" data-searchable="false"><?= I18N::translate('Is running?') ?></th>
            <th data-sortable="false" data-searchable="false"><?= I18N::translate('Run task') ?></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<?php View::pushunique('javascript')?>

<script src="<?= e($js_script_url) ?>"></script>

<?php View::endpushunique() ?>

<?php View::push('javascript') ?>
<script>
let renderOptions = { _ : "display", sort: "raw", filter: "raw" };

var adminTasksTable = $(".table-maj-admintasks-list").DataTable({
    ajax:                {
      url: "<?= e($tasks_data_route) ?>"
    },
    autoWidth:           false,
    columns: [
        /* 0 Edit               */ { className: "text-center", data: "edit"},
        /* 1 Enabled            */ { className: "text-center", data: "status", render: renderOptions},
        /* 2 Task Title         */ { className: "text-center", data: "task_name", render: renderOptions},
        /* 3 Last Run           */ { className: "text-center", data: "last_run", render: renderOptions},
        /* 4 Last status        */ { className: "text-center", data: "last_result", render: renderOptions},
        /* 5 Frequency          */ { className: "text-center", data: "frequency"},
        /* 6 Nb Occcurrences    */ { className: "text-center", data: "nb_occurrences"},
        /* 7 Is Running         */ { className: "text-center", data: "running"},
        /* 8 Run task           */ { className: "text-center", data: "run"}
    ],
    sorting:             [[2, "asc"]],
});

function generate_force_token() {
    $('#force-token-generate').attr('disabled', 'disabled');
    $('#force-token-generate div').addClass('d-none');
    $('#force-token-generate .fa-spinner').removeClass('d-none');
    $.post({
        url: "<?= e($new_token_route) ?>",
        dataType: 'json',
        success: function(data) {
            $("#token_url").html(data.token);
            $('#force-token-generate').removeAttr('disabled');
            $('#force-token-generate div').removeClass('d-none');
            $('#force-token-generate .fa-spinner').addClass('d-none');
            adminTasksTable.ajax.reload();
        }
    });
}

function maj_run_admintask(taskid, route) {
    $('#run-task-button-' + taskid).attr('disabled', 'disabled');
    $('#run-task-button-' + taskid + ' .maj-loading-initial').addClass('d-none');
    $('#run-task-button-' + taskid + ' .maj-loading-inprocess').removeClass('d-none');
    $.post({
        url: route
    }).done(function() {
        $('#run-task-button-' + taskid + ' .maj-loading-complete').removeClass('d-none');
    }).fail(function() {
        $('#run-task-button-' + taskid + ' .maj-loading-error').removeClass('d-none');
    }).always(function() {
        $('#run-task-button-' + taskid).removeAttr('disabled');
        $('#run-task-button-' + taskid + ' .maj-loading-inprocess').addClass('d-none');
        setTimeout(() => { adminTasksTable.ajax.reload(); }, 1000);
    });
} 
</script>
<?php View::endpush() ?>
