<?php

use Fisharebest\Webtrees\I18N;

/**
 * @var int     $task_sched_id
 * @var string  $run_route
 */

?>

<button type="button" class="btn btn-primary" id="run-task-button-<?= $task_sched_id ?>" onclick="maj_run_admintask(<?= $task_sched_id ?>, '<?= $run_route ?>')">
    <div class="maj-loading-initial">
        <span class="maj-icon-run"><i class="fa-solid fa-play"></i></span>
        &nbsp;<?= e(I18N::translate('Run')) ?>
    </div>
    <i class="fa-solid fa-spinner fa-pulse fa-fw d-none maj-loading-inprocess"></i>
    <div class="maj-loading-complete d-none">
        <span class="maj-icon-done"><i class="fa-solid fa-check"></i></span>
        &nbsp;<?= e(I18N::translate('Done')) ?>
    </div>
    <div class="maj-loading-error d-none">
        <span class="maj-icon-error"><i class="fa-solid fa-times"></i></span>
        &nbsp;<?= e(I18N::translate('Error')) ?>
    </div>
</button>
<button type="button" class="btn btn-outline-secondary"
    title="<?= e(I18N::translate('Copy trigger URL')) ?>" 
    onclick="maj_copy_admintask_trigger(<?= $task_sched_id ?>)"
    >
    <?= view('icons/copy') ?>
</button>
<input id="maj-task-trigger-url-<?= $task_sched_id ?>" type="hidden" value="<?= e($run_route) ?>" />
