<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ModulesAllPage;
use Illuminate\Support\Collection;
use MyArtJaub\Webtrees\Module\Certificates\Http\RequestHandlers\AdminConfigPage;

/**
 * @var string      $title
 * @var Collection  $trees
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ModulesAllPage::class) => I18N::translate('Modules'), $title]]) ?>

<h1><?= $title ?></h1>

<p><?= I18N::translate('Select a tree to modify its configuration for the “Certificates” module.') ?></p>

<table class="table table-bordered table-hover table-sm maj-certificate-table-admin-trees"
    <?= view('lists/datatables-attributes') ?>
    data-info="false"
    data-paging="false"
    data-filter="false"
>

    <thead>
        <tr>
            <th>
                <?= I18N::translate('Tree') ?>
            </th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($trees as $tree) : ?>
            <tr>
                <th scope="row" dir="auto">
                    <a href="<?= route(AdminConfigPage::class, ['tree' => $tree->name() ]) ?>"><?= $tree->title() ?></a>
                </th>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

<?php View::push('javascript') ?>
<script>
  'use strict';

  $(".maj-certificate-table-admin-trees").dataTable();
</script>
<?php View::endpush() ?>