<?php

use Fisharebest\Webtrees\I18N;

/**
 * @var array<string, string[]> $titles
 */



?>

<div class="accordion-item">
    <div class="accordion-header" id="name-header-maj-titles">
        <button class="accordion-button collapsed gap-1" type="button" data-bs-toggle="collapse" data-bs-target="#name-content-maj-titles" aria-expanded="false" aria-controls="name-content-maj-titles">
            <?= view('icons/expand') ?>
            <?= view('icons/collapse') ?>
            <span class="label"><?= I18N::translate('Titles') ?></span>
        </button>
    </div>
    <div id="name-content-maj-titles" class="accordion-collapse collapse" data-bs-parent="#individual-names" aria-labelledby="name-header-maj-titles">
        <div class="accordion-body">
            <dl class="row mb-0">
                <?php foreach ($titles as $title => $lands) : ?>
                    <?php $nb_lands = count($lands) ?>
                <dt class="col-md-4 col-lg-3"><?= $title ?></dt>
                <dd class="col-md-8 col-lg-9">
                    <bdi>
                        <?= $title ?>
                        <?php if ($nb_lands === 1) : ?>
                            <?= $lands[0] ?>
                        <?php elseif ($nb_lands > 1) : ?>
                            <?php usort($lands, I18N::comparator()) ?>
                            <?= implode(I18N::$list_separator, array_slice($lands, 0, $nb_lands - 1)) . I18N::translate(', and ') ?>
                            <?= $lands[$nb_lands - 1] ?>
                        <?php endif; ?>
                    </bdi>
                </dd>
                <?php endforeach; ?>
            </dl>
        </div>
    </div>
</div>