<?php

use Fisharebest\Webtrees\I18N;

/**
 * @var array<string, string[]> $titles
 */



?>

<div class="card">
    <div class="card-header" role="tab" id="name-header-maj-titles">
        <a data-toggle="collapse" href="#name-content-maj-titles" aria-expanded="false" aria-controls="name-content--maj-titles">
            <?= view('icons/expand') ?>
            <?= view('icons/collapse') ?>
            <span class="label"><?= I18N::translate('Titles') ?></span>
        </a>
    </div>
    <div id="name-content-maj-titles" class="card-body collapse" data-parent="#individual-names" aria-labelledby="name-header-maj-titles">
        <dl class="row mb-0">
            <?php foreach ($titles as $title => $lands) : ?>
                <?php $nb_lands = count($lands) ?>
            <dt class="col-md-4 col-lg-3"><?= $title ?></dt>
            <dd class="col-md-8 col-lg-9">
                <span dir="auto">
                    <?= $title ?>
                    <?php if ($nb_lands === 1) : ?>
                        <?= $lands[0] ?>
                    <?php elseif ($nb_lands > 1) : ?>
                        <?php usort($lands, I18N::comparator()) ?>
                        <?= implode(I18N::$list_separator, array_slice($lands, 0, $nb_lands - 1)) . I18N::translate(', and ') ?>
                        <?= $lands[$nb_lands - 1] ?>
                    <?php endif; ?>
                </span>
            </dd>
            <?php endforeach; ?>
        </dl>
    </div>
</div>