<?php

use Fisharebest\Webtrees\Factory;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Http\RequestHandlers\Select2Individual;
use MyArtJaub\Webtrees\Module\Sosa\Http\RequestHandlers\SosaConfigAction;

/**
 * @var string                  $module_name
 * @var string                  $title
 * @var Tree                    $tree
 * @var int                     $user_id
 * @var int                     $selected_user_id
 * @var bool                    $immediate_compute
 * @var array<string,mixed>     $users_root
 */

?>

<h2 class="wt-page-title mx-auto"><?= e($title) ?></h2>

<div class="wt-page-content wt-page-content-maj-sosa-config">
    <form name="maj-sosa-config-form" method="post" action="<?= e(route(SosaConfigAction::class, ['tree' => $tree->name()])) ?>" class="wt-page-options hidden-print mb-4">
        <?= csrf_field() ?>
        <div class="row form-group">
            <label class="col-sm-3 col-form-label wt-page-options-label">
                <?= I18N::translate('Tree') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <label><?= e($tree->title()) ?></label>
            </div>
        </div>
        
        <!-- SOSA USER ID -->
        <div class="form-group">
            <div class="row">
                <label class="col-sm-3 col-form-label wt-page-options-label" for="maj-sosa-select-userid">
                    <?= I18N::translate('For user') ?>
                </label>
                <div class="col-sm-9 wt-page-options-value">
                    <?php if (count($users_root) == 1) : ?>
                        <?php $root_id = $users_root[0]['root_id']; ?>
                        <div class="col-sm-9 wt-page-options-value">
                            <input id="maj-sosa-input-userid" type="hidden" name="sosa-userid" value="<?php echo $users_root[0]['user']->id(); ?>" />
                            <label><?= e($users_root[0]['user']->realName()) ?></label>
                        </div>
                    <?php elseif (count($users_root) > 1) : ?>
                        <?php $root_id = $users_root[0]['root_id']; ?>
                        <select id="maj-sosa-select-userid" name="sosa-userid" class="form-control">
                            <?php foreach ($users_root as $i => $user_root) : ?>
                                <?php if ($user_root['user']->id() == $selected_user_id) {
                                    $root_id = $user_root['root_id'];
                                    $selected = true;
                                } else {
                                    $selected = $i == 0;
                                }?>
                                <option value="<?= $user_root['user']->id() ?>" <?= $selected ? 'selected' : '' ?>>
                                    <?= e($user_root['user']->realName()) ?>
                                </option>   
                            <?php endforeach; ?>
                        </select>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        
        <!-- SOSA ROOT ID -->
        <div class="form-group">
            <div class="row">
                <label class="col-sm-3 col-form-label wt-page-options-label" for="maj-sosa-input-rootid">
                    <?= I18N::translate('Root individual') ?>
                </label>
                <div class="col-sm-9 wt-page-options-value">
                    <?= view('components/select-individual', ['name' => 'sosa-rootid', 'individual' => Factory::individual()->make($root_id, $tree), 'tree' => $tree]) ?>
                </div>
            </div>
        </div>
        
        <div class="row form-group">
            <label class="col-sm-3 col-form-label wt-page-options-label"></label>
            <div class="col-sm-9 wt-page-options-value">
                <button type="submit" class="btn btn-primary">
                    <?= view('icons/save') ?>
                    <?= I18N::translate('save') ?>
                </button>
                
                <?= view($module_name . '::config-compute-button', [
                    'tree' => $tree,
                    'user_select_id' => '#maj-sosa-input-userid, #maj-sosa-select-userid option:selected',
                    'immediate_compute' => $immediate_compute,
                    'selected_user_id' => $selected_user_id
                ]) ?>
            </div>
        </div>
        
    </form> 
    
</div>

<?php View::push('javascript') ?>
<script>

var users_array = [];

<?php foreach ($users_root as $user_root) : ?>
users_array["<?= $user_root['user']->id() ?>"] = "<?= $user_root['root_id'] ?>";
<?php endforeach; ?>

$('#maj-sosa-select-userid').change(function() {
    $.ajax({
        type: 'POST',
        url: '<?= e(route(Select2Individual::class, ['tree' => $tree->name(), 'at' => ''])) ?>',
        data: { q: users_array[this.value] }
    }).then(function (data) {
        if(data.results.length > 0) {
            result = data.results[0];
        
            // create the option and append to Select2
            var option = new Option(result.text, result.id, true, true);
            $('#sosa-rootid').append(option).trigger('change');
    
            // manually trigger the `select2:select` event
            $('#sosa-rootid').trigger({
                type: 'select2:select',
                params: {
                    data: result
                }
            });
        }
        else {
            $('#sosa-rootid').val(null).trigger('change');
        }
    });
    
    //$("#sosa-rootid").val(users_array[this.value]);
    //$("#sosa-rootid").trigger('change');
});

</script>
<?php View::endpush() ?>
