<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Module\ModuleThemeInterface;
use Illuminate\Support\Collection;
use MyArtJaub\Webtrees\Module\Sosa\Http\RequestHandlers\PedigreeCollapseData;

/**
 * @var string                          $module_name
 * @var string                          $title
 * @var Tree                            $tree
 * @var ModuleThemeInterface            $theme
 * @var Individual|NULL                 $root_indi
 * @var array<string, int|float>        $general_stats
 * @var array<int, <string, int|float>> $generation_stats
 * @var object                          $generation_depth
 * @var Collection                      $multiple_sosas
 * @var Collection                      $sosa_dispersion_g2
 * @var Collection                      $sosa_dispersion_g3
 * @var Collection                      $gen_depth_g3
 */

?>

<h2 class="wt-page-title mx-auto"><?= e($title) ?></h2>

<div class="wt-page-content wt-page-content-maj-sosa-statistics">
<?php if ($root_indi === null) : ?>
    <?= view($module_name . '::errors/no-sosa-defined') ?>

<?php else : ?>
    <?php if ($root_indi->canShowName()) : ?>
<h4 class="text-center m-3"><?= I18N::translate('%s: %s', I18N::translate('Root individual'), $root_indi->fullName()) ?></h4>
    <?php endif;?>

    <?= view($module_name . '::statistics-general-table', ['general_stats' => $general_stats]) ?>

    <?= view($module_name . '::statistics-generations-table', ['tree' => $tree, 'generation_stats' => $generation_stats, 'generation_depth' => $generation_depth]) ?>

    <?= view($module_name . '::statistics-multisosa-table', ['tree' => $tree, 'multiple_sosas' => $multiple_sosas]) ?>

    <?= view($module_name . '::statistics-dispersion-chart', ['module_name' => $module_name, 'theme' => $theme, 'sosa_dispersion_g2' => $sosa_dispersion_g2, 'sosa_dispersion_g3' => $sosa_dispersion_g3]) ?>

    <?= view($module_name . '::statistics-generationdepth-chart', ['module_name' => $module_name, 'theme' => $theme, 'tree' => $tree, 'gen_depth_g3' => $gen_depth_g3]) ?>

<?php endif; ?>
</div>

<?php View::push('javascript') ?>
<script>

    $.when($.getJSON('<?= e(route(PedigreeCollapseData::class, ['tree' => $tree->name() ])) ?>'), $.ready)
    .done(function(data, unused) {
        $('.maj-sosa-pedicollapse-globalvalue').text(data[0].pedi_collapse);
        var cells = data[0].cells;
        $('.maj-sosa-pedicollapse-cell').each(function() {
            var gen = $(this).data('sosa-gen');
            $(this).replaceWith(cells.hasOwnProperty(gen) ? cells[gen] : '&hellip;');
        });
        
        $('.maj-sosa-pedicollapse .maj-loading-complete').removeClass('d-none');
    }).fail(function() {
        $('.maj-sosa-pedicollapse .maj-loading-error').removeClass('d-none');
    }).always(function() {
        $('.maj-sosa-pedicollapse .maj-loading-initial').addClass('d-none');
    });

</script>
<?php View::endpush() ?>
