<?php 

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Functions\Functions;
use Fisharebest\Webtrees\Module\ModuleThemeInterface;
use Illuminate\Support\Collection;
use Fisharebest\Webtrees\Statistics\Service\ColorService;

/**
 * @var string                  $module_name
 * @var ModuleThemeInterface    $theme
 * @var Collection              $sosa_dispersion_g2
 * @var Collection              $sosa_dispersion_g3
 */
?>

<h3 class="text-center m-3"><?= I18N::translate('Known Sosa ancestors\' family dispersion'); ?></h3>

<div class="maj-sosa-dispersion-charts text-center">
<?= view($module_name . '::charts/pie', [
    'colors'            =>  [
        $theme->parameter('chart-background-m'),
        $theme->parameter('chart-background-u'),
        $theme->parameter('chart-background-f')
    ],
    'data'              => [
        ["Branche", 'Count'],
        [Functions::getRelationshipNameFromPath('fat'), (int) $sosa_dispersion_g2->get(1, 0)],
        [I18N::translate('Shared'), (int) $sosa_dispersion_g2->get(0, 0)],
        [Functions::getRelationshipNameFromPath('mot'), (int) $sosa_dispersion_g2->get(2, 0)]
    ],
    'pieStartAngle'     => 180,
    'labeledValueText'  => 'percentage',
    'language'          => I18N::languageTag(),
    'height'            => 250,
    'width'             => '50%'
]) ?>
    
    
<?= view($module_name . '::charts/pie', [
    'colors'            =>  [
        app(ColorService::class)->interpolateRgb($theme->parameter('chart-background-m'), '#00000', 10)[1],
        $theme->parameter('chart-background-m'),
        $theme->parameter('chart-background-u'),
        app(ColorService::class)->interpolateRgb($theme->parameter('chart-background-f'), '#00000', 10)[1],
        $theme->parameter('chart-background-f'),
    ],
    'data'              => [
        ["Branche", 'Count'],
        [Functions::getRelationshipNameFromPath('fatfat'), (int) $sosa_dispersion_g3->get(1, 0)],
        [Functions::getRelationshipNameFromPath('fatmot'), (int) $sosa_dispersion_g3->get(2, 0)],
        [I18N::translate('Shared'), (int) $sosa_dispersion_g3->get(0, 0)],
        [Functions::getRelationshipNameFromPath('motfat'), (int) $sosa_dispersion_g3->get(3, 0)],
        [Functions::getRelationshipNameFromPath('motmot'), (int) $sosa_dispersion_g3->get(4, 0)]
    ],
    'pieStartAngle'     => 180,
    'labeledValueText'  => 'percentage',
    'language'          => I18N::languageTag(),
    'height'            => 260,
    'width'             => '50%'
]) ?>
</div>