<?php

use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\MediaFile;

/**
 * @var Individual $individual
 */

?>

<?php if ($individual->findHighlightedMediaFile() instanceof MediaFile) : ?>
    <?= $individual->findHighlightedMediaFile()->displayImage(30, 40, 'crop', []) ?>
<?php endif; ?>
<?= $individual->fullName() ?>, <?= $individual->lifespan() ?>
<!--  MYARTJAUB-START -->
<?= hook(\MyArtJaub\Webtrees\Contracts\Hooks\RecordNameTextExtenderInterface::class,
    fn(\MyArtJaub\Webtrees\Contracts\Hooks\RecordNameTextExtenderInterface $hook) => $hook->recordNameAppend($individual),
    '')
    ?>
<!--  MYARTJAUB-END -->
