<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string  $route_name
 * @var Tree    $tree
 * @var int     $min_gen
 * @var int     $max_gen
 * @var int     $current_gen
 */

// GET request from a form will not pass the parameters in the action attribute, so the route needs to be set as hidden input
$route_url = route($route_name, [ 'tree' => $tree->name() ]);
$route_params = [];
parse_str(parse_url($route_url, PHP_URL_QUERY) ?? '', $route_params);
$route = $route_params['route'] ?? '';

?>
<form method="GET" name="generation-selector" action="<?= e(route($route_name, [ 'tree' => $tree->name() ])) ?>">
    <?php if ($route !== '') : ?>
    <input type="hidden" name="route" value="<?= e($route) ?>">
    <?php endif; ?>
    <div class="maj-sosa-table mx-auto">
        <div class="maj-sosa-row">
            <div class="wt-page-options-label"><?= I18N::translate('Choose generation') ?></div>
        </div>
        <div class="maj-sosa-row">
            <div class="wt-page-options-value">
                <select name="gen">
                <?php for ($i = $min_gen; $i <= $max_gen; $i++) : ?>
                    <option value="<?= $i; ?>"  <?=  $current_gen === $i ? 'selected' : '' ?>>
                        <?= I18N::translate('Generation %s', I18N::number($i)) ?>
                    </option>
                <?php endfor; ?>
                </select>
            </div>
        </div>
        <div class="maj-sosa-row">
            <div class="py-2 text-center">
                <input type="submit" class="btn btn-primary" value="<?= e(I18N::translate('Show')) ?>" />
            </div>
        </div>
    </div>
    <br />
</form>
