<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string  $route_name
 * @var Tree    $tree
 * @var int     $min_gen
 * @var int     $max_gen
 * @var int     $current_gen
 */

?>

<form method="GET" name="generation-selector" action="<?= route($route_name, [ 'tree' => $tree->name() ]) ?>">
    <div class="maj-sosa-table mx-auto">
        <div class="maj-sosa-row">
            <div class="wt-page-options-label"><?= I18N::translate('Choose generation') ?></div>
        </div>
        <div class="maj-sosa-row">
            <div class="wt-page-options-value">
                <select name="gen">                         
                <?php for ($i = $min_gen; $i <= $max_gen; $i++) : ?>
                    <option value="<?= $i; ?>"  <?=  $current_gen === $i ? 'selected' : '' ?>>
                        <?= I18N::translate('Generation %d', $i) ?>
                    </option>
                <?php endfor; ?>
                </select>
            </div>
        </div>
        <div class="maj-sosa-row">
            <div class="py-2 text-center">
                <input type="submit" class="btn btn-primary" value="<?= e(I18N::translate('Show')) ?>" />
            </div>
        </div>
    </div>
    <br />
</form>
