<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string  $route_name
 * @var Tree    $tree
 * @var int     $min_gen
 * @var int     $max_gen
 * @var int     $current_gen
 */

?>

<?php if ($current_gen > 0) : ?>
<h4 class="text-center">
    <?php if ($current_gen > $min_gen) : ?>
    <a href="<?= route($route_name, ['tree' => $tree->name(), 'gen' => min($max_gen, $current_gen - 1)]) ?>" title="<?= e(I18N::translate('Previous generation'))?>">
        <?= view('icons/arrow-left') ?>
    </a>
    &nbsp;&nbsp;
    <?php endif; ?>
    <?= I18N::translate('Generation %d', $current_gen) ?>
    <?php if ($current_gen < $max_gen) : ?>
    &nbsp;&nbsp;
    <a href="<?= route($route_name, ['tree' => $tree->name(), 'gen' => max($min_gen, $current_gen + 1)]) ?>" title="<?= e(I18N::translate('Next generation'))?>">
        <?= view('icons/arrow-right') ?>
    </a>
    <?php endif; ?>
</h4>
<?php endif;?>
