<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Age;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;

/**
 * @var string                      $module_name
 * @var Tree                        $tree
 * @var \Illuminate\Support\Collection<int, \Fisharebest\Webtrees\Family>   $families
 */

 // lists require a unique ID in case there are multiple lists per page
$table_id = Registry::idFactory()->id('table-ancestors-fam-');

$today_jd          = Registry::timestampFactory()->now()->julianDay();
$hundred_years_ago = Registry::timestampFactory()->now()->subtractYears(100)->julianDay();

?>

<!-- MYARTJAUB-START -->
<?php
    $maj_columns = hook(
        \MyArtJaub\Webtrees\Contracts\Hooks\SosaFamilyDatatablesExtenderInterface::class,
        fn(\MyArtJaub\Webtrees\Module\Hooks\Hooks\SosaFamilyDatatablesExtenderCollector $hook) => $hook->sosaFamilyColumns($families)
    ) ?? [];
    $maj_issourced_marr = $maj_columns['issourced']['marr'] ?? null;

    $column_indexes = [];
    foreach ($maj_columns as $maj_columns_mod) {
        foreach ($maj_columns_mod as $maj_column) {
            $column_indexes[] = $maj_column['position'] ?? null;
        }
    }
    $column_indexes = collect($column_indexes)->filter();
    ?>
<!-- MYARTJAUB-END -->

<?php View::push('javascript') ?>
<script>
$("#<?= e($table_id) ?> > .maj-table-ancestors-family").dataTable({
    processing: true,
    retrieve: true,
    columns: [
        /* Sosa              */ { type: "num" },
        /* Given names       */ { type: "text" },
        /* Surnames          */ { type: "text" },
        /* Age               */ { type: "num" },
        /* Given names       */ { type: "text" },
        /* Surnames          */ { type: "text" },
        /* Age               */ { type: "num" },
        /* Marriage date     */ { type: "num" },
        /* Marriage place    */ { type: "text" },
        //MYARTJAUB-START
        <?= $maj_issourced_marr !== null ? json_encode($maj_issourced_marr['column_def'], JSON_THROW_ON_ERROR) . ', ' : '' ?>
        //MYARTJAUB-END
        /* Children          */ { type: "num" },
        /* Filter marriage   */ { sortable: false },
        /* Filter alive/dead */ { sortable: false },
        /* Filter tree       */ { sortable: false }
    ],
    sorting: [
        [0, "asc"]
    ]
});

$("#<?= e($table_id) ?>")
    /* Hide/show parents */
    .on("click", "#btn-toggle-parents", function() {
        $(".wt-individual-list-parents").slideToggle();
    })
    /* Filter buttons in table header */
    .on("click", "input[data-filter-column]", function() {
        let checkbox = $(this);

        // Deselect other options
        let siblings = checkbox.siblings("input[type='checkbox']");
        siblings.prop("checked", false).removeAttr("checked");

        // Apply (or clear) this filter
        let checked = checkbox.prop("checked");
        let filter  = checked ? checkbox.data("filter-value") : "";
        let column  = $("#<?= e($table_id) ?> .maj-table-ancestors-family").DataTable().column(checkbox.data("filter-column"));
        column.search(filter).draw();
    });
</script>
<?php View::endpush() ?>

<div id="<?= e($table_id) ?>">
    <table class="table table-bordered table-sm maj-table-ancestors-family"        
        <?= view($module_name . '::lists/datatables-attributes', [ 'length_menu' => [ 16, 32, 64, 200, 1000, -1 ]]) ?>
    >
        <thead>
            <tr>
                <!--  MYARTJAUB-START -->
                <th colspan="<?= columnIndex(13, $column_indexes) ?>">
                    <div class="btn-toolbar d-flex justify-content-between mb-2">
                        <div class="btn-group btn-group-sm" role="group">
                            <input id="<?= e($table_id) ?>-bg-dead-N" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(11, $column_indexes) ?>" data-filter-value="N" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-dead-N" class="btn btn-outline-secondary btn-sm" title="' . I18N::translate('Show individuals who are alive or couples where both partners are alive.') ?>">
                                <?= I18N::translate('Both alive') ?>
                            </label>

                            <input id="<?= e($table_id) ?>-bg-dead-W" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(11, $column_indexes) ?>" data-filter-value="W" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-dead-W" class="btn btn-outline-secondary" title="<?= I18N::translate('Show couples where only the female partner is dead.') ?>">
                                <?= I18N::translate('Widower') ?>
                            </label>

                            <input id="<?= e($table_id) ?>-bg-dead-H" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(11, $column_indexes) ?>" data-filter-value="H" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-dead-H" class="btn btn-outline-secondary" title="<?= I18N::translate('Show couples where only the male partner is dead.') ?>">
                                <?= I18N::translate('Widow') ?>
                            </label>

                            <input id="<?= e($table_id) ?>-bg-dead-Y" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(11, $column_indexes) ?>" data-filter-value="Y" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-dead-Y" class="btn btn-outline-secondary" title="<?= I18N::translate('Show individuals who are dead or couples where both partners are dead.') ?>">
                                <?= I18N::translate('Both dead') ?>
                            </label>
                        </div>

                        <div class="btn-group btn-group-sm" role="group">
                            <input id="<?= e($table_id) ?>-bg-roots-R" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(12, $column_indexes) ?>" data-filter-value="R" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-roots-R" class="btn btn-outline-secondary" title="<?= I18N::translate('Show “roots” couples or individuals. These individuals may also be called “patriarchs”. They are individuals who have no parents recorded in the database.') ?>">
                                <?= I18N::translate('Roots') ?>
                            </label>
                        </div>

                        <div class="btn-group btn-group-sm" role="group">
                            <input id="<?= e($table_id) ?>-bg-marr-U" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(10, $column_indexes) ?>" data-filter-value="U" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-marr-U" class="btn btn-outline-secondary" title="<?= I18N::translate('Show couples with an unknown marriage date.') ?>">
                                <?= I18N::translate('Not married') ?>
                            </label>

                            <input id="<?= e($table_id) ?>-bg-marr-YES" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(10, $column_indexes) ?>" data-filter-value="YES" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-marr-YES" class="btn btn-outline-secondary" title="<?= I18N::translate('Show couples who married more than 100 years ago.') ?>">
                                <?= I18N::translate('Marriage') ?>&gt;100
                            </label>

                            <input id="<?= e($table_id) ?>-bg-marr-Y100" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(10, $column_indexes) ?>" data-filter-value="Y100" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-marr-Y100" class="btn btn-outline-secondary" title="<?= I18N::translate('Show couples who married within the last 100 years.') ?>">
                                <?= I18N::translate('Marriage') ?>&lt;=100
                            </label>

                            <input id="<?= e($table_id) ?>-bg-marr-D" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(10, $column_indexes) ?>" data-filter-value="D" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-marr-D" class="btn btn-outline-secondary" title="<?= I18N::translate('Show divorced couples.') ?>">
                                <?= I18N::translate('Divorce') ?>
                            </label>

                            <input id="<?= e($table_id) ?>-bg-marr-M" class="btn-check" type="checkbox" data-filter-column="<?= columnIndex(10, $column_indexes) ?>" data-filter-value="M" autocomplete="off">
                            <label for="<?= e($table_id) ?>-bg-marr-M" class="btn btn-outline-secondary" title="<?= I18N::translate('Show couples where either partner married more than once.') ?>">
                                <?= I18N::translate('Multiple marriages') ?>
                            </label>
                        </div>
                    </div>
                </th>
            </tr>
            <tr>
                <th class="text-center"><?= I18N::translate('Sosa') ?></th>
                <th><?= I18N::translate('Given names') ?></th>
                <th><?= I18N::translate('Surname') ?></th>
                <th><?= I18N::translate('Age') ?></th>
                <th><?= I18N::translate('Given names') ?></th>
                <th><?= I18N::translate('Surname') ?></th>
                <th><?= I18N::translate('Age') ?></th>
                <th><?= I18N::translate('Marriage') ?></th>
                <th><?= I18N::translate('Place') ?></th>
                <!--  MYARTJAUB-START -->
                <?php if ($maj_issourced_marr !== null) : ?>
                <th><?= $maj_issourced_marr['th'] ?></th>
                <?php endif; ?>
                <!--  MYARTJAUB-END -->
                <th><i class="icon-children" title="<?= I18N::translate('Children') ?>"></i></th>
                <th hidden></th>
                <th hidden></th>
                <th hidden></th>
            </tr>
        </thead>

        <tbody>
        <?php foreach ($families as $sosa => $family) : ?>
            <?php $husb = $family->husband() ?? Registry::individualFactory()->new('H', '0 @H@ INDI', null, $family->tree()) ?>
            <?php $wife = $family->wife() ?? Registry::individualFactory()->new('W', '0 @W@ INDI', null, $family->tree()) ?>
            
            <tr class="<?= $family->isPendingAddition() ? 'wt-new' : '' ?> <?= $family->isPendingDeletion() ? 'wt-old' : '' ?>">
                <td class="maj-cell-sosa text-center" data-sort="<?= $sosa ?>"><?= I18N::number($sosa) ?>/<?= I18N::number($sosa % 10 + 1) ?></td>
                <!-- Husband name -->
                <td colspan="2" data-sort="<?= e(str_replace([',', Individual::PRAENOMEN_NESCIO, Individual::NOMEN_NESCIO], 'AAAA', implode(',', array_reverse(explode(',', $husb->sortName()))))) ?>">
                    <?php foreach ($husb->getAllNames() as $num => $name) : ?>
                    <div>
                        <?php if ($name['type'] !== '_MARNM' || $num == $husb->getPrimaryName()) : ?>
                        <a title="<?= $name['type'] === '_MARNM' ? I18N::translate('Married name') :  '' ?>" href="<?= e($family->url()) ?>" class="<?= $num === $husb->getPrimaryName() ? '' : 'text-muted' ?>">
                            <?= $name['full'] ?>
                        </a>
                            <?php if ($num === $husb->getPrimaryName()) : ?>
                                <small><?= view('icons/sex', ['sex' => $husb->sex()]) ?></small>
                            <?php endif ?>
                        <?php endif ?>
                    </div>
                    <?php endforeach ?>
                    <?= view('lists/individual-table-parents', ['individual' => $husb]) ?>
                </td>

                <td hidden data-sort="<?= e(str_replace([',', Individual::PRAENOMEN_NESCIO, Individual::NOMEN_NESCIO], 'AAAA', $husb->sortName())) ?>"></td>

                <!-- Husband age -->
                <?php $age  = new Age($husb->getBirthDate(), $family->getMarriageDate()) ?>
                <td class="text-center" data-sort="<?= $age->ageDays() ?>">
                    <?= $age->ageYearsString() ?>
                </td>

                <!-- Wife name -->
                <td colspan="2" data-sort="<?= e(str_replace([',', Individual::PRAENOMEN_NESCIO, Individual::NOMEN_NESCIO], 'AAAA', implode(',', array_reverse(explode(',', $wife->sortName()))))) ?>">
                    <?php foreach ($wife->getAllNames() as $num => $name) : ?>
                    <div>
                        <?php if ($name['type'] !== '_MARNM' || $num == $wife->getPrimaryName()) : ?>
                            <a title="<?= $name['type'] === '_MARNM' ? I18N::translate('Married name') :  '' ?>" href="<?= e($family->url()) ?>" class="<?= $num === $wife->getPrimaryName() ? '' : 'text-muted' ?>">
                                <?= $name['full'] ?>
                            </a>
                            <?php if ($num === $wife->getPrimaryName()) : ?>
                                <small><?= view('icons/sex', ['sex' => $wife->sex()]) ?></small>
                            <?php endif ?>
                        <?php endif ?>
                    </div>
                    <?php endforeach ?>
                    <?= view('lists/individual-table-parents', ['individual' => $wife]) ?>
                </td>

                <td hidden data-sort="<?= e(str_replace([',', Individual::PRAENOMEN_NESCIO, Individual::NOMEN_NESCIO], 'AAAA', $wife->sortName())) ?>"></td>

                <!-- Wife age -->
                <?php $age = new Age($wife->getBirthDate(), $family->getMarriageDate()) ?>
                <td class="text-center" data-sort="<?= $age->ageDays() ?>">
                    <?= $age->ageYearsString() ?>
                </td>

                <!-- Marriage date -->
                <td data-sort="<?= $family->getMarriageDate()->julianDay() ?>">
                    <?php $marriage_dates = $family->getAllMarriageDates(); ?>
                    <?php if (count($marriage_dates) > 0) : ?>
                        <?php foreach ($marriage_dates as $marriage_date) : ?>
                            <div><?= $marriage_date->display($tree) ?></div>
                        <?php endforeach ?>
                    <?php elseif ($family->facts(['MARR'])->isEmpty()) : ?>
                        <?= I18N::translate('no') ?>
                    <?php elseif ($family->facts(['MARR'])->isNotEmpty()) : ?>
                            <?= I18N::translate('yes') ?>
                    <?php endif ?>
                </td>

                <!-- Marriage place -->
                <td data-sort="<?= e($family->getMarriagePlace()->gedcomName()) ?>">
                    <?php foreach ($family->getAllMarriagePlaces() as $marriage_place) : ?>
                        <div><?= $marriage_place->shortName(true) ?></div>
                    <?php endforeach ?>
                </td>

                <!--  MYARTJAUB-START -->
                <!-- IsSourced Marriage -->
                <?php if ($maj_issourced_marr !== null) : ?>
                <td data-sort="<?= $maj_issourced_marr['records'][$sosa]['order'] ?? 0 ?>">
                    <?= $maj_issourced_marr['records'][$sosa]['text'] ?? '' ?>
                </td>
                <?php endif; ?>
                <!--  MYARTJAUB-END -->

                <!-- Number of children -->
                <td class="text-center" data-sort="<?= $family->numberOfChildren() ?>">
                    <?= I18N::number($family->numberOfChildren()) ?>
                </td>

                <!-- Filter by marriage date -->
                <td hidden>
                    <?php if ($family->getMarriageDate()->maximumJulianDay() > $hundred_years_ago && $family->getMarriageDate()->maximumJulianDay() <= $today_jd) : ?>
                        Y100
                    <?php elseif ($family->facts(['MARR'])->isNotEmpty()) : ?>
                        YES
                    <?php else : ?>
                        U
                    <?php endif ?>
                    <?php if ($family->facts(['DIV'])->isNotEmpty()) : ?>
                        D
                    <?php endif ?>
                    <?php if (count($husb->spouseFamilies()) > 1 || count($wife->spouseFamilies()) > 1) : ?>
                        M
                    <?php endif ?>
                </td>

                <!-- Filter by alive/dead -->
                <td hidden>
                    <?php if ($husb->isDead() && $wife->isDead()) : ?>
                        Y
                    <?php endif ?>
                    <?php if ($husb->isDead() && !$wife->isDead()) : ?>
                        <?php if ($wife->sex() === 'F') : ?>
                            H
                        <?php endif ?>
                        <?php if ($wife->sex() === 'M') : ?>
                            W
                        <?php endif ?>
                    <?php endif ?>
                    <?php if (!$husb->isDead() && $wife->isDead()) : ?>
                        <?php if ($husb->sex() === 'M') : ?>
                            W
                        <?php endif ?>
                        <?php if ($husb->sex() === 'F') : ?>
                            H
                        <?php endif ?>
                    <?php endif ?>
                    <?php if (!$husb->isDead() && !$wife->isDead()) : ?>
                        N
                    <?php endif ?>
                </td>

                <!-- Filter by roots/leaves -->
                <td hidden>
                    <?php if ($husb->childFamilies()->isEmpty() && $wife->childFamilies()->isEmpty()) : ?>
                        R
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>

        <tfoot>
            <tr>
                <th colspan="<?= columnIndex(13, $column_indexes) ?>">
                    <div class="btn-group btn-group-sm">
                        <input type="checkbox" class="btn-check" id="btn-toggle-parents" autocomplete="off" data-wt-persist="families-parents">
                        <label class="btn btn-secondary" for="btn-toggle-parents">
                            <?= I18N::translate('Show parents') ?>
                        </label>
                    </div>
                </th>
            </tr>
        </tfoot>
    </table>
</div>
