name: Code style StyleLint CSS / SCSS

on:
   push:
      branches-ignore:
         - '**-dev'
   pull_request:

jobs:

  stylelint:
    runs-on: ubuntu-latest
    name: StyleLint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions-hub/stylelint@master
        env:
          PATTERN: "modules_v4/myartjaub_*/src/**/*.scss"