name: Code style StyleLint CSS / SCSS

on:
   push:
      branches-ignore:
         - '**-dev'
   pull_request:

jobs:

  stylelint:
    runs-on: ubuntu-latest
    name: StyleLint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: npm install stylelint stylelint-config-standard stylelint-config-sass-guidelines

      - name: Run StyleLint
        run: npx stylelint "modules_v4/myartjaub_*/src/**/*.scss"
