<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use MyArtJaub\Webtrees\Module\WelcomeBlock\Http\RequestHandlers\MatomoStats;

/**
 * @var int     $block_id
 * @var string  $fab_welcome_block_view
 * @var string  $fab_login_block_view
 * @var bool    $matomo_enabled
 */

?>

<?= $fab_welcome_block_view ?>

<?php if ($matomo_enabled) : ?>
<div class="d-flex flex-wrap justify-content-around text-center">
    <div id="maj-matomo-stats-<?= $block_id ?>">
        <div class="maj-loading-initial">
            <i class="fas fa-spinner fa-pulse fa-fw"></i>
            &nbsp;<?= I18N::translate('Retrieving Matomo statistics...') ?>
        </div>
        <div class="maj-loading-complete d-none text-center"></div>
        <div class="maj-loading-error d-none text-center">
            <?= I18N::translate('No statistics could be retrieved from Matomo.') ?>
        </div>
    </div>
</div>
<?php endif; ?>

<hr />

<?= $fab_login_block_view ?>

<?php View::push('javascript') ?>
<script>
$(document).ready( function() {
    $.get("<?= route(MatomoStats::class, ['block_id' => $block_id]) ?>")
    .done(function(data) {
        $('#maj-matomo-stats-<?= $block_id ?> .maj-loading-complete')
            .removeClass('d-none')
            .html(data);
    }).fail(function() {
        $('#maj-matomo-stats-<?= $block_id ?> .maj-loading-error').removeClass('d-none');
    }).always(function() {
        $('#maj-matomo-stats-<?= $block_id ?> .maj-loading-initial').addClass('d-none');
    });
});
</script>
<?php View::endpush() ?>
