<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

/**
 * @var bool    $matomo_enabled
 * @var string  $matomo_url
 * @var string  $matomo_token
 * @var int     $matomo_siteid
 */

?>

<!-- MATOMO_ENABLED -->
<div class="row form-group">
    <label class="col-sm-3 col-form-label" for="matomo_enabled">
        <?= I18N::translate('Enable Matomo Statistics') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/radios-inline', ['name' => 'matomo_enabled', 'options' => [ 'yes' => I18N::translate('yes'), 'no' => I18N::translate('no') ],  'selected' => $matomo_enabled ? 'yes' : 'no']) ?>
    </div>
</div>

<div id="matomo_config" class="d-none">

    <!-- MATOMO_URL -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="matomo_url">
            <?= I18N::translate('Matomo URL') ?>
        </label>
        <div class="col-sm-9">
            <input
                class="form-control"
                name="matomo_url"
                type="url"
                value="<?= e($matomo_url) ?>"
            >
        </div>
    </div>
    
    <!-- MATOMO_TOKEN -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="matomo_token">
            <?= I18N::translate('Matomo Token') ?>
        </label>
        <div class="col-sm-9">
            <input
                class="form-control"
                name="matomo_token"
                type="text"
                value="<?= e($matomo_token) ?>"
            >
        </div>
    </div>
    
    <!-- MATOMO_SITE_ID -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="matomo_siteid">
            <?= I18N::translate('Matomo Site ID') ?>
        </label>
        <div class="col-sm-2">
            <input
                class="form-control"
                name="matomo_siteid"
                min="1"
                type="number"
                value="<?= e($matomo_siteid) ?>"
            >
        </div>
    </div>
</div>

<?php View::push('javascript') ?>
<script>

function toggleMatomoConfig() {
    if($('input:radio[name="matomo_enabled"]:checked').val() == 'yes') {
        $('#matomo_config').removeClass('d-none');
    }
    else {
        $('#matomo_config').addClass('d-none');
    }
}

$('[name="matomo_enabled"]').on('change', toggleMatomoConfig);
toggleMatomoConfig();

</script>
<?php View::endpush() ?>
