<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;

/**
 * @var int|NULL $visits_year
 * @var int|NULL $visits_today
 */

?>

<?php if ($visits_year !== null) : ?>
    <?= I18N::translate(
        '%1$s visits since the beginning of %2$s<br>(%3$s today)',
        '<span class="odometer">' . I18N::number($visits_year) . '</span>',
        Registry::timestampFactory()->now()->format('Y'),
        '<span class="odometer">' . I18N::number($visits_today ?? 0) . '</span>'
    ); ?>
<?php else : ?>
    <?= I18N::translate('No statistics could be retrieved from Matomo.') ?>
<?php endif;?>
