<?php 


use Fisharebest\Webtrees\Carbon;
use Fisharebest\Webtrees\I18N;

/**
 * @var int $visits_year
 * @var int $visits_today
 */

?>

<?php if($visits_year !== null) : ?>
	<?= I18N::translate('%1$s visits since the beginning of %2$s<br>(%3$s today)' ,
	    '<span class="odometer">' . I18N::number($visits_year) . '</span>',
        Carbon::now()->year,
	    '<span class="odometer">' . I18N::number($visits_today ?? 0) . '</span>'
        ); ?>
<?php else : ?>
	<?= I18N::translate('No statistics could be retrieved from Matomo.') ?>
<?php endif;?>